language: csharp
solution: src/Provausio.ResttClient.sln
install:
  - nuget restore src/Provausio.Rest.Client.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/RestClient.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.x86.exe src/Provausio.Rest.Client.Test/bin/Release/Provausio.Rest.Client.Test.dll
