language: csharp
solution: src/RestClient.sln
#install:
#  - nuget restore src/RestClient.sln
#  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
#script:
#  - xbuild /p:Configuration=Release src/RestClient.sln
#  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.x86.exe src/RestClient.Test/bin/Release/RestClient.Test.dll
