language: csharp
solution: src/RestClient.sln
install:
  - nuget restore src/RestClient.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/RestClient.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe src/RestClient.Test/bin/Release/RestClient.Test.dll
